"""empty message

Revision ID: 382e1f28533b
Revises: de6e81b2dc6c
Create Date: 2024-03-06 13:48:10.206080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382e1f28533b'
down_revision = 'de6e81b2dc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
